### ISSUE TITLE
`packaging` requirement

### ISSUE THREAD

**Issue by sungwonh** [greenbone/autohooks#322]
Is it possible to update `packaging` library to support version >=21.0?
https://github.com/greenbone/autohooks/blob/main/pyproject.toml#L50

**Comment by bjoernricks** [comment]
@sungwonh do you need a new release (on pypi)?

**Comment by sungwonh** [comment]
@bjoernricks Yes, I need. Thank you in advance!

**Comment by bjoernricks** [comment]
done :-)

**Comment by sungwonh** [comment]
@bjoernricks 

`pontos` also depends on `packaging`.
I submitted an issue https://github.com/greenbone/pontos/issues/357.

Thanks in advance!

**Comment by bjoernricks** [comment]
I'll take a look
