### ISSUE TITLE
Supported mypy plugin

### ISSUE THREAD

**Issue by codebutler** [greenbone/autohooks#364]
Hi,

Someone published [autohooks-plugin-mypy](https://pypi.org/project/autohooks-plugin-mypy) but there's no source repository so it's effectively unmaintained.  Could an official plugin be created?

Thanks

**Comment by bjoernricks** [comment]
Yes I've that pypi project too as I wanted to start a mypy plugin. Sadly that name is taken now. To answer your question. Yes there will be a mypy plugin but currently due to other more important tasks I can't give a timeline.

**Comment by bjoernricks** [comment]
Forgot to mention we did take over the ownership of the authooks mypy plugin https://github.com/greenbone/autohooks-plugin-mypy/
