### ISSUE TITLE
Request to add ruff

### ISSUE THREAD

**Issue by jorgegomzar** [greenbone/autohooks#564]
Hi! I've recently discovered your project and immediately added a bunch of autohooks plugins to my projects.

I wanted to add ruff pre-commit so I followed your [documentation](https://greenbone.github.io/autohooks/create.html#formatting-plugin) and created my [own](https://github.com/jorgegomzar/autohooks-plugin-ruff) by creating a fork of your pylint plugin.

What is your usual workflow for this? Should I publish the plugin to PyPI or would you rather create a fork to keep everything under the same team?

Thanks for everything, love your work!

**Comment by bjoernricks** [comment]
Hi,

as this is the second request for a ruff plugin (first was #511) and I also want to play with ruff in near future so I am in favor of creating an "official" ruff plugin in the greenbone space. 

Would it be ok for you if I take your code as the base? Or should I create an initial repo and you are going to rebase your commits against that repo and create a PR?

**Comment by jorgegomzar** [comment]
Whichever is easier for you guys!

**Comment by bjoernricks** [comment]
Because I wont have that much time next week, it is easiest if you create a PR against https://github.com/greenbone/autohooks-plugin-ruff

**Comment by jorgegomzar** [comment]
Got it! I've cleaned the code a bit + added git config to the docker dev env.
Here is the PR https://github.com/greenbone/autohooks-plugin-ruff/pull/1

**Comment by bjoernricks** [comment]
Created a release on pypi https://pypi.org/project/autohooks-plugin-ruff/
