### ISSUE TITLE
When creating a custom hook in .authooks directory I get: No module named 'autohooks.plugin.flake8'

### ISSUE THREAD

**Issue by Lyonsclay** [greenbone/autohooks#75]
├── .autohooks
  ├── __init__.py
  └── flake8.py

__init__.py - 

```
from .flake8 import precommit
```

pyproject.toml -

```
[tool.autohooks]
mode = "pipenv"
pre-commit = ["autohooks.plugins.black","autohooks.plugins.flake8"]
```

I'm not sure how to make the plugin available to autohook. 

Full error;

ℹ     Running autohooks.plugins.flake8
          An error occurred while importing pre-commit hook autohooks.plugins.flake8. No module named 
          'autohooks.plugins.flake8'.

**Comment by bjoernricks** [comment]
`.autohooks` is just added to the `PYTHONPATH`. If you specify a `"autohooks.plugins.flake8"` plugin autohooks will try to import this module. So your path must be `.autohooks/autohooks/plugins/flake8.py`. Would be easier to rename it to something like `flakeplugin.py` in import is as `pre-commit = ["autohooks.plugins.black","flakeplugin"]`. Hopefully my answer is understandable.

**Comment by bjoernricks** [comment]
Closing this issue now. Feel free to reopen if your issue still persists.
