### ISSUE TITLE
Windows Problem

### ISSUE THREAD

**Issue by anujydv** [greenbone/autohooks#77]
`poetry run autohooks activate` not working, giving  `KeyError` PWD and after setting it manually, it's not performing any autohooks task as define in pyproject.toml.

**Comment by bjoernricks** [comment]
Could you please paste the full traceback? Without the traceback we can't debug this issue any further.

**Comment by anujydv** [comment]
Please check attached images
![MicrosoftTeams-image](https://user-images.githubusercontent.com/20188072/96954863-f1c85f00-1511-11eb-9ddb-f9f153d2412f.png)
After setting it manually `set PWD=<project_dir>` hooks setup completed but 'git commit' not working.

**Comment by An-Li-magicloud** [comment]
I have the same problem, from the log, it seems activate treats autohooks.exe as a folder?
``C:\Users\ali\AppData\Local\pypoetry\Cache\virtualenvs\tidy3d-webapi-qWdOphEq-py3.8\Scripts\autohooks.exe\__main__.py``

**Comment by bjoernricks** [comment]
@An-Li-magicloud could you please create a new issue for your problem and provide a complete traceback? Your issue is completely unrelated. The original issue has been fixed with https://github.com/greenbone/autohooks/pull/165 already a long time ago.
